default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SUQ-App_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SUQ-App_test

production:
  <<: *default
  adapter: mysql2
  database: SQU-App_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost