default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SUQ-App_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: SUQ-App_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  database: SQU-App_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock