default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SQU-App_development
  socket: /run/mysqld/mysqld.sock
  

test:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SQU-App_test

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: SQU-App_production
  username: squuser
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  port: 3306
