default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SUQ-App_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: fvju0301
  host: localhost
  database: SUQ-App_test

production:
  <<: *default
  adapter: postgresql
  database: SQU-App_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock